---
kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  ports:
    - port: 8080
      targetPort: http-server
  selector:
    app: frontend
  type: LoadBalancer
